# Тема “Вычисления с помощью Numpy”
## Задание 1.
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать,
что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по
каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в
нем должно быть 2 элемента.

In [1]:
import numpy as np

Создадим список (list) первого столбца

In [2]:
a = [1, 2, 3, 3, 1]

Создадим список (list) второго столбца

In [3]:
b = [6, 8, 11, 10, 7]

Создаем массив numpy, поместив списки в функцию array

In [4]:
C = np.array ([a , b])
C

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

При заполнении строк массива получилась матрица размером 2х5, нам нужна размерность 5х2. Значит необходимо применить фунуцию транспонирования матриц

с помощью функции np.transpose : A_t = np.transpose(A)

с помощью метода A.transpose : A_t = A.transpose()

с помощью атрибута A.T : A_t = A.T

In [5]:
D = C.T
D

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [6]:
type (D)

numpy.ndarray

Теперь выполняем в одно действие

In [7]:
E = (np.array([a,b])).T
E

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

Или:
Создайем массив Numpy под названием a размером 5x2

In [8]:
a = (np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
print("Среднее значение для каждого столбца: {}".format(a.mean(axis=0)))

Среднее значение для каждого столбца: [2.  8.4]


Результат - массив mean_a :

In [10]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

## Задание 2.
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих
признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

Применим концепцию Broadcasting:

In [11]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

## Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться
величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [12]:
a1 = a_centered[0:,0]
a2 = a_centered[0:,1]
print (a1)
print (a2)

[-1.  0.  1.  1. -1.]
[-2.4 -0.4  2.6  1.6 -1.4]


In [13]:
a_centered_sp = a1.dot(a2)
print("Скалярное произведение столбцов массива a_centered:", a_centered_sp)

Скалярное произведение столбцов массива a_centered: 8.0


In [14]:
# Также вычсилсить скалярное произведение, возможно используя транспонированную матрицу
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [15]:
# С помощью атрибута size можно увидеть общее количество элементов массива:

In [16]:
print(f'Число наблюдений N является количестом строк и равно: {a[:,0].size}')

Число наблюдений N является количестом строк и равно: 5


In [17]:
N = a[:,0].size
print(f'(N-1) = {N - 1}')

(N-1) = 4


In [18]:
print(f'Результат деления a_centered_sp/(N-1) = {a_centered_sp/(a[:,0].size - 1)}')

Результат деления a_centered_sp/(N-1) = 2.0


In [22]:
cov_matrix = np.cov(a.T)
print("Ковариационная матрица:\n", cov_matrix)
print("Значение ковариации = ", cov_matrix[0,1])

Ковариационная матрица:
 [[1.  2. ]
 [2.  4.3]]
Значение ковариации =  2.0


### Задание 4**

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся
в массиве “а”. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на
N, поэтому полученная нами величина является несмещенной оценкой ковариации.
Подробнее узнать о ковариации можно здесь:
Выборочная ковариация и выборочная дисперсия — Студопедия
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с
помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать
транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером
2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом
1.
Тема

In [25]:
cov1 = a_centered_sp/(a[:,0].size - 1)
print (cov1)
cov_m = np.cov(a.T)
print (cov_m)
cov2 = cov_m[0,1]
print (cov2)
assert cov1 == cov2
print('Значения ковариации, вычисленные разными способами равны')

2.0
[[1.  2. ]
 [2.  4.3]]
2.0
Значения ковариации, вычисленные разными способами равны
